#!/usr/bin/env bash
# Compile the core IN-TREE and REPORT THE TIMING, not just the exit code.
#
#     scripts/build.sh            # full compile
#     scripts/build.sh --map      # analysis & synthesis only (fast syntax check)
#     scripts/build.sh --report   # re-read the last build's reports, compile nothing
#
# Quartus reports "Fitter was successful" on a design that grossly fails
# timing, and nothing in the default flow warns you -- so output_files/<rev>.sta.summary
# is read here, every time, and a timing failure is as loud as a syntax error.
#
# Prefer scripts/build_staged.py: it builds HEAD in a worktree and leaves the
# tree free. This one sees uncommitted work and needs the tree left alone.
set -euo pipefail

[ -d sys ] || { echo "run me from the repository root"; exit 1; }

# Tool locations: the environment, then the core's mister.env, then the
# standard install path. Probed, because "bash" here may be WSL's, which
# cannot run Windows .exe tools at all.
[ -f mister.env ] && { set -a; . ./mister.env; set +a; }
Q=""
for _c in "${QUARTUS_BIN:-}" /c/intelFPGA_lite/17.0/quartus/bin64 C:/intelFPGA_lite/17.0/quartus/bin64; do
	[ -n "$_c" ] && [ -x "$_c/quartus_sh.exe" ] && Q="$_c" && break
done
[ -n "$Q" ] || { echo "Quartus not found. Set QUARTUS_BIN."; exit 1; }
# The revision: CORE_REV, else the one .qsf in the core root.
REV="${CORE_REV:-$(ls *.qsf 2>/dev/null | head -1 | sed "s/\.qsf$//")}"
[ -n "$REV" ] || { echo "no .qsf here: run from the core root"; exit 1; }
OUT=output_files

mode="${1:-full}"

if [ "$mode" != "--report" ]; then
	# The other half of scripts/hwlock.py: no compile while a JTAG tool reads.
	python scripts/hwlock.py --require-no-jtag "build.sh $REV"
	mkdir -p "$OUT"
	# build_id.v is generated by the PRE_FLOW script, which only runs for a
	# real flow. quartus_map on its own does not trigger it, and the missing
	# file reads as a confusing `can't open Verilog Design File`.
	"$Q/quartus_sh.exe" -t sys/build_id.tcl x "$REV" "$REV" >/dev/null

	if [ "$mode" = "--map" ]; then
		"$Q/quartus_map.exe" --read_settings_files=on --write_settings_files=off \
			"$REV" -c "$REV" 2>&1 | tee "$OUT/build.log" | grep -E "^Error|^\s+Error" || true
		grep -qE "^Error" "$OUT/build.log" && { echo "SYNTHESIS FAILED"; exit 1; }
		echo "analysis & synthesis OK"
		exit 0
	fi

	"$Q/quartus_sh.exe" --flow compile "$REV" -c "$REV" > "$OUT/build.log" 2>&1 || {
		echo "COMPILE FAILED"; grep -E "^Error|^\s+Error" "$OUT/build.log" | head -20; exit 1; }
fi

echo
echo "==== resource usage ===================================================="
# .fit.summary is a plain "key : value" list with no banner to key a range on.
grep -E "Logic utilization|Total registers|Total block memory bits|Total RAM Blocks|Total DSP Blocks|Total pins|Total PLLs" \
	"$OUT/$REV.fit.summary" || echo "(no $OUT/$REV.fit.summary)"

echo
echo "==== timing ============================================================"
if [ -f "$OUT/$REV.sta.summary" ]; then
	cat "$OUT/$REV.sta.summary"
else
	echo "no $OUT/$REV.sta.summary -- STA did not run"
	exit 1
fi

# A negative slack anywhere is a failure, whatever the fitter said.
if grep -qE "Slack[[:space:]]*:[[:space:]]*-" "$OUT/$REV.sta.summary"; then
	echo
	echo "*** TIMING NOT MET -- negative slack above. The .rbf is not trustworthy. ***"
	exit 1
fi

echo
if [ -f "$OUT/$REV.rbf" ]; then
	ls -l "$OUT/$REV.rbf"
	echo "timing met."
else
	echo "no .rbf produced"
	exit 1
fi
