#!/usr/bin/env python3
"""Turn a MAME debugger trace into an expected FETCH list for the testbench.

    python scripts/parse_mame_trace.py <trace.tr> <out.txt> [--past-loops]

MAME's trace lists one INSTRUCTION START per line. The RTL testbench records
every instruction FETCH, extension words included -- `clr.w $4067ec.l` is one
MAME line and three fetches. So the two are not directly comparable.

This expands MAME's PCs into the words actually fetched. Where two consecutive
PCs are a small positive distance apart, the instruction occupies exactly that
many words and they are emitted: cur, cur+2, ... next-2. Where the distance is
negative or large (a branch, jump or call), only the PC itself is emitted,
because its length is not knowable from the trace alone.

The testbench then matches this list as an in-order SUBSEQUENCE of its own
fetch trace, which tolerates the few unexpanded branch instructions while
still failing loudly on a real divergence.

Two markers bound the usable region:

  "(loops for N instructions)"  MAME collapses loops unless traced with
      `noloop`. Parsing STOPS here by default: a boot delay loop typically runs
      131,068 instructions, which the RTL would need ~5M clk cycles to grind
      through, so a routine regression cannot reach past it. --past-loops
      continues anyway, for a deliberately long run.

  "(interrupted at ..., IRQ n)" always stops it. Past this point MAME is
      executing an ISR, and the testbench's boot case runs with no interrupts
      asserted -- they are no longer the same program.
"""
import re, sys

def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    past = '--past-loops' in sys.argv
    if len(args) != 2:
        sys.exit(__doc__)
    src, dst = args

    pcs, stop = [], None
    for line in open(src, encoding='utf-8', errors='replace'):
        s = line.strip()
        if s.startswith('(interrupted'):
            stop = s
            break
        if s.startswith('(loops'):
            if not past:
                stop = s
                break
            continue
        m = re.match(r'^([0-9A-Fa-f]{6,8}):\s', s)
        if m:
            pcs.append(int(m.group(1), 16))

    words, expanded, branches = [], 0, 0
    for i, pc in enumerate(pcs):
        nxt = pcs[i+1] if i + 1 < len(pcs) else None
        if nxt is not None and 0 < (nxt - pc) <= 12:
            for a in range(pc, nxt, 2):
                words.append(a)
            expanded += 1
        else:
            words.append(pc)
            branches += 1

    with open(dst, 'w') as f:
        f.write("// Expected instruction-fetch addresses, from a MAME debugger trace.\n")
        f.write("// Generated by scripts/parse_mame_trace.py -- do not hand-edit.\n")
        f.write(f"// source: {src}\n")
        f.write("// Match as an in-order SUBSEQUENCE of the RTL fetch trace.\n")
        for a in words:
            f.write(f"{a:08x}\n")

    print(f"{len(pcs)} instructions -> {len(words)} fetch words -> {dst}")
    print(f"  {expanded} expanded from PC deltas, {branches} branch/jump PCs left unexpanded")
    print(f"  range {pcs[0]:06X}..{pcs[-1]:06X}")
    if stop:
        print(f"  stopped at: {stop}")
main()
